apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/Ameausoone/discover-kustomize/iso/base?ref=master

namePrefix: remote-

patchesStrategicMerge:
  - deployment.yaml

configMapGenerator:
  - name: my-config
    literals:
      - app_env=dev
      - app_db_host=dbhost
      - app_demo=cncfmeetup

images:
  - name: nginx
    newTag: latest
    newName: ameausoone/env
